# News Sources Configuration
news_sources:
  reuters:
    base_url: "https://www.reuters.com/markets/companies"
    article_selector: "article.story"
    title_selector: "h3.story-title"
    content_selector: "div.story-content"
    max_pages: 10
    request_delay: 2

  bloomberg:
    base_url: "https://www.bloomberg.com/markets"
    article_selector: "article.article-card"
    title_selector: "h3.article-title"
    content_selector: "div.article-body"
    max_pages: 10
    request_delay: 2

  yahoo_finance:
    base_url: "https://finance.yahoo.com/news"
    article_selector: "div.Ov(h)"
    title_selector: "h3.Mb(5px)"
    content_selector: "div.article-content"
    max_pages: 10
    request_delay: 1

# Social Media Configuration
social_media:
  twitter:
    search_terms:
      - "$AAPL"
      - "$GOOGL"
      - "$MSFT"
      - "$AMZN"
      - "$META"
    max_tweets_per_term: 1000
    languages: ["en"]
    exclude_retweets: true
    min_followers: 100

  reddit:
    subreddits:
      - "wallstreetbets"
      - "stocks"
      - "investing"
      - "cryptocurrency"
    post_limit: 500
    comment_limit: 1000
    min_score: 10

# Data Storage
storage:
  raw_data_path: "../data/raw"
  processed_data_path: "../data/processed"
  database:
    host: "localhost"
    port: 5432
    name: "financial_sentiment"
    user: "postgres"

# Scraping Settings
settings:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  headers:
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    Accept-Language: "en-US,en;q=0.5"
  timeout: 30
  retry_attempts: 3
  retry_delay: 5
  verify_ssl: false  # Temporarily disable SSL verification for testing

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "scraping.log"
